openapi: 3.0.1
paths:
  /random/{format}:
    get:
      tags:
        - Page content
      summary: Get content for a random page
      description: |
        Redirects the client to the URI for the desired format for a random page title.

        Stability: [unstable](https://www.mediawiki.org/wiki/API_versioning#Unstable)
      parameters:
        - name: format
          in: path
          description: The desired return format
          required: true
          schema:
            type: string
            enum:
              - title
              - html
              - summary
              - related
              - mobile-sections
              - mobile-sections-lead
      responses:
        303:
          description: The redirect to the desired format URI for a random page
          content:
            application/json; charset=utf-8; profile="https://www.mediawiki.org/wiki/Specs/Random/0.6.0":
              schema:
                type: object
        default:
          description: Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/problem'
      x-request-handler:
        - title_from_mobileapps:
            request:
              uri: '{{options.host}}/{domain}/v1/page/random/title'
            return:
              status: 303
              headers:
                cache_control: '{{options.random_cache_control}}'
                location: ../{request.params.format}/{title_from_mobileapps.body.items[0].title}
      x-monitor: false
