openapi: 3.0.1
info:
  version: 1.0.0-beta
  title: MediaWiki Related Pages API
  description: Related pages API
  termsOfService: https://github.com/wikimedia/restbase#restbase
  contact:
    name: Services
    email: services@lists.wikimedia.org
    url: https://www.mediawiki.org/wiki/Services
  license:
    name: Apache licence, v2
    url: https://www.apache.org/licenses/LICENSE-2.0
paths:
  /related/{title}:
    get:
      tags:
        - Page content
      summary: Get pages related to the given title
      description: |
        Returns summaries for 20 pages related to the given page. Summaries include
        page title, namespace and id along with short text description of the page
        and a thumbnail.

        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental)
      parameters:
        - name: title
          in: path
          description: 'Page title. Use underscores instead of spaces. Example: `Main_Page`.'
          required: true
          schema:
            type: string
      responses:
        200:
          description: The related pages
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/related'
        404:
          description: Unknown page title
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/problem'
        default:
          description: Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/problem'
      operationId: getRelatedPages
      x-monitor: false

components:
  schemas:
    related:
      type: object
      properties:
        pages:
          type: array
          items:
            $ref: '#/components/schemas/summary'
