openapi: 3.0.1
info:
  version: 1.0.0
  title: Global Transform API
  description: Global Transform API
  termsOfService: https://github.com/wikimedia/restbase
  license:
    name: Apache licence, v2
    url: https://www.apache.org/licenses/LICENSE-2.0
paths:
  /html/from/{from_lang}/to/{to_lang}:
    post: &html_from_lang_to_lang_post_spec
      tags: 
        - Transform
      summary: Machine-translate content
      description: |
        Fetches the machine translation for the posted content from the source
        to the destination language.

        Stability: [unstable](https://www.mediawiki.org/wiki/API_versioning#Unstable)
      parameters:
        - name: from_lang
          in: path
          description: The source language code
          required: true
          schema:
            type: string
        - name: to_lang
          in: path
          description: The target language code
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
                - html
              properties:
                html:
                  type: string
                  description: The HTML content to translate
                  x-textarea: true
        required: true
      responses:
        200:
          description: The translated content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cx_mt'
        default:
          description: Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/problem'
      x-monitor: false
      x-request-handler:
        - get_from_cx:
            request:
              method: post
              uri: '{{options.cx_host}}/v1/mt/{from_lang}/{to_lang}/{provider}'
              body:
                html: '{{html}}'

  /html/from/{from_lang}/to/{to_lang}/{provider}:
    post:
      <<: *html_from_lang_to_lang_post_spec
      parameters:
        - name: from_lang
          in: path
          description: The source language code
          required: true
          schema:
            type: string
        - name: to_lang
          in: path
          description: The target language code
          required: true
          schema:
            type: string
        - name: provider
          in: path
          description: The machine translation provider id
          required: true
          schema:
            type: string
            enum:
              - Apertium
              - Yandex
              - Youdao
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - html
              properties:
                html:
                  type: string
                  description: The HTML content to translate
                  x-textarea: true
        required: true

  /word/from/{from_lang}/to/{to_lang}/{word}:
    get: &word_from_lang_to_lang_word_get_spec
      tags: 
        - Transform
      summary: Fetch the dictionary meaning of a word
      description: |
        Fetches the dictionary meaning of a word from a language and displays
        it in the target language.

        Stability: [unstable](https://www.mediawiki.org/wiki/API_versioning#Unstable)
      parameters:
        - name: from_lang
          in: path
          description: The source language code
          required: true
          schema:
            type: string
        - name: to_lang
          in: path
          description: The target language code
          required: true
          schema:
            type: string
        - name: word
          in: path
          description: The word to lookup
          required: true
          schema:
            type: string
      responses:
        200:
          description: the dictionary translation for the given word
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cx_dict'
        default:
          description: Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/problem'
      x-monitor: false
      x-request-handler:
        - get_from_cx:
            request:
              uri: '{{options.cx_host}}/v1/dictionary/{word}/{from_lang}/{to_lang}/{provider}'

  /word/from/{from_lang}/to/{to_lang}/{word}/{provider}:
    get:
      <<: *word_from_lang_to_lang_word_get_spec
      parameters:
        - name: from_lang
          in: path
          description: The source language code
          required: true
          schema:
            type: string
        - name: to_lang
          in: path
          description: The target language code
          required: true
          schema:
            type: string
        - name: word
          in: path
          description: The word to lookup
          required: true
          schema:
            type: string
        - name: provider
          in: path
          description: The dictionary provider id
          required: true
          schema:
            type: string
            enum:
              - JsonDict
              - Dictd

  /list/pair/{from}/{to}/:
    get:
      tags:
        - Transform
      summary: Lists the tools available for a language pair
      description: |
        Fetches the list of tools that are available for the given pair of languages.

        Stability: [unstable](https://www.mediawiki.org/wiki/API_versioning#Unstable)
      parameters:
        - name: from
          in: path
          description: The source language code
          required: true
          schema:
            type: string
        - name: to
          in: path
          description: The target language code
          required: true
          schema:
            type: string
      responses:
        200:
          description: the list of tools available for the language pair
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cx_list_tools'
        default:
          description: Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/problem'
      x-monitor: false
      x-request-handler:
        - get_from_cx:
            request:
              uri: '{{options.cx_host}}/v1/list/pair/{from}/{to}'
  /list/tool/{tool}:
    get: &list_tool_tool_get_spec
      tags:
        - Transform
      summary: Lists the tools and language pairs available for the given tool category
      description: |
        Fetches the list of tools and all of the language pairs it can translate

        Stability: [unstable](https://www.mediawiki.org/wiki/API_versioning#Unstable)
      parameters:
        - name: tool
          in: path
          description: The tool category to list tools and language pairs for
          required: true
          schema:
            type: string
            enum:
              - mt
              - dictionary
      responses:
        200:
          description: the list of language pairs available for a given translation
            tool
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cx_list_pairs_for_tool'
        default:
          description: Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/problem'
      x-monitor: false
      x-request-handler:
        - get_from_cx:
            request:
              uri: '{{options.cx_host}}/v1/list/{tool}'

  /list/tool/{tool}/{from}/{to}:
    get:
      <<: *list_tool_tool_get_spec
      parameters:
        - name: tool
          in: path
          description: The tool category to list tools and language pairs for
          required: true
          schema:
            type: string
            enum:
              - mt
              - dictionary
        - name: from
          in: path
          description: The source language code
          required: true
          schema:
            type: string
        - name: to
          in: path
          description: The target language code
          required: true
          schema:
            type: string
      x-request-handler:
        - get_from_cx:
            request:
              uri: '{{options.cx_host}}/v1/list/{tool}/{from}/{to}'

  /list/languagepairs/:
    get:
      tags:
        - Transform
      summary: Lists the language pairs supported by the back-end
      description: |
        Fetches the list of language pairs the back-end service can translate

        Stability: [unstable](https://www.mediawiki.org/wiki/API_versioning#Unstable)
      responses:
        200:
          description: the list of source and target languages supported by the API
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cx_languagepairs'
      x-monitor: false
      x-request-handler:
        - get_from_cx:
            request:
              uri: '{{options.cx_host}}/v1/list/languagepairs'

components:
  schemas:
    cx_list_tools:
      type: object
      properties:
        tools:
          type: array
          description: the list of tools available for the given language pair
          items:
            type: string
            description: the tool available
    cx_list_pairs_for_tool:
      type: object
    cx_languagepairs:
      type: object
      properties:
        source:
          type: array
          description: the list of available source languages
          items:
            type: string
            description: one source language
        target:
          type: array
          description: the list of available destination languages
          items:
            type: string
            description: one destination language
