openapi: 3.0.1
info:
  version: '1.0.0'
  title: RESTBase key-value module
  description: >
    Blob storage with HTTP interface, backed by table storage.

    All headers prepended with `x-store-` are saved on write and returned
    with the content upon retrieval. All the not prepended headers not stored.
paths:
  /{bucket}:
    put:
      operationId: createBucket
  /{bucket}/{key}:
    get:
      operationId: getRevision
    put:
      operationId: putRevision

