swagger: '2.0'
info:
  version: '1.0.0'
  title: RESTBase multi-content-bucket module
  description: Revisioned blob storage with HTTP interface, backed by table storage
paths:
  /:
    put:
      operationId: createBucket
  /{content}/{key}: &content_key
    get:
      operationId: getRevision

  /{content}/{key}/:
    get:
      operationId: listRevisions

  /{content}/{key}/{revision}:
    <<: *content_key

  /{content}/{key}/{revision}/{tid}:
    <<: *content_key

  /all/{key}/{revision}: &all_key_revision
    put:
      operationId: putRevision

  /all/{key}/{revision}/{tid}:
    <<: *all_key_revision
