swagger: '2.0'
info:
  version: '1.0.0'
  title: RESTBase post data storage module
  description: Revisioned post data storage with HTTP interface, backed by table storage
paths:
  /{bucket}:
    put:
      operationId: createBucket

  /{bucket}/:
    put:
      operationId: putRevision

  /{bucket}/{key}: &bucket_key
    get:
      operationId: getRevision
  /{bucket}/{key}/{tid}:
    <<: *bucket_key

  /{bucket}/hash:
    post:
      operationId: calculateHash
